slam_gmapping:
  base_frame: base_footprint
  odom_frame: odom
  map_update_interval: 30.0
  maxUrange: 50.0
  sigma: 0.05
  kernelSize: 1
  lstep: 0.05
  astep: 0.05
  iterations: 5
  lsigma: 0.075
  ogain: 3.0
  lskip: 0
  srr: 0.01
  srt: 0.02
  str: 0.01
  stt: 0.02
  linearUpdate: 0.3
  angularUpdate: 0.2
  temporalUpdate: -1.0
  resampleThreshold: 0.5
  particles: 80
  xmin: -100.0
  ymin: -100.0
  xmax: 100.0
  ymax: 100.0
  delta: 0.025
  llsamplerange: 0.01
  llsamplestep: 0.01
  lasamplerange: 0.005
  lasamplestep: 0.005
  minimumScore : 0.0